### ISSUE TITLE
Create separate github repository for transforms

### ISSUE THREAD

**Issue by markus-hinsche** [kbressem/trainlib#14]
As an example: `MulticlassSegNrrdToOneHot` is duplicated across multiple repos. 

Should this go into a common repo, e.g. trainlib (even better would be MONAI of course)?

**Comment by kbressem** [comment]
The best would be MONAI. However, there is a major issue I found which is not yet solved. 

The affine matrix of `seg.nrrd`is 4x3 with the first row beeing just `nan`. This is because the first dimension on the voxel array is the channel, which, naturally, has no spatial dimensions. However, in `monai`, the affine matrix is converted from `RAS` to `LPS`, which is done by matrix multiplication of the affine matrix with itself. However, this transforms the affine matrix to only `nan` and produces errors for all later affine transforms. Although, this problem is in the `NrrdReader`, or, more specifically in `monai.data.utils.orientation_ras_lps`, it prevents `seg.nrrd` files to be used in monai and thus `MulticlassSegNrrdToOneHot` is of no use for `monai`, yet. 

Therefore, `MulticlassSegNrrdToOneHot` is currently duplicated across repos. Furthermore, I still have the feeling the transform does not work properly, as it occasionally throws errors.

Should we solve these issues, I would like to contribute it to monai.

**Comment by markus-hinsche** [comment]
I just took `MulticlassSegNrrdToOneHot` as an example. I wanted to discuss here how to deal with custom transforms in general, as I foresee that there will be more custom transforms. 

We could consider: A new repo e.g. https://github.com/rAIdiance/rAIdiance-transforms/ to work on these transforms. As soon as they can be promoted to MONAI the leave `rAIdiance-transforms` and are maintained in MONAI. However, until they are in MONAI, there is some value in co-developing them across multiple user repos

**Comment by kbressem** [comment]
Agreed. I don't think there is a point including them in `trainlib`. But having a repo with custom transforms would be good, so we don't duplicate code all over different repos. I'll tend to it

**Comment by kbressem** [comment]
Add possibility to trainlib, to load transforms via the web

**Comment by kbressem** [comment]
Repo is available at https://github.com/kbressem/transforms
